### ISSUE TITLE
Rating on iPhone not displayed correctly

### ISSUE THREAD

**Issue by muescha** [nirlom/gatsby-theme-cv#1]
![BF76DDA3-8D76-4D52-9285-C8C3E1BEA003](https://user-images.githubusercontent.com/184316/64923549-06003f80-d7db-11e9-8233-d56c6a93dc75.png)

On iPhone with Safari the rating is not correct

**Comment by mhjadav** [comment]
Hello @muescha,

Very sorry for the delayed response, Thank you so much for letting us know about the issue.

We have fixed the issue, you can check it out at [cv.mojaave.com](https://cv.mojaave.com)

Thanks

**Comment by nirlom-team** [comment]
Closing this issue, after testing if you find it feel free to reopen.

Thanks
